export const MODALIDAD_OCUPACION = {
  POR_HORA: 'POR_HORA',
  DIARIA: 'DIARIA',
  SEMANAL: 'SEMANAL',
  ABONO: 'ABONO'
} as const

export type ModalidadOcupacion =
  (typeof MODALIDAD_OCUPACION)[keyof typeof MODALIDAD_OCUPACION]

export const MODALIDAD_OCUPACION_LABEL: Record<ModalidadOcupacion, string> = {
  [MODALIDAD_OCUPACION.POR_HORA]: 'Por hora',
  [MODALIDAD_OCUPACION.DIARIA]: 'Diario',
  [MODALIDAD_OCUPACION.SEMANAL]: 'Semanal',
  [MODALIDAD_OCUPACION.ABONO]: 'Abono'
}

export const MODALIDAD_OCUPACION_ESPORADICA = {
  POR_HORA: MODALIDAD_OCUPACION.POR_HORA,
  DIARIA: MODALIDAD_OCUPACION.DIARIA,
  SEMANAL: MODALIDAD_OCUPACION.SEMANAL
} as const

export type ModalidadOcupacionEsporadica =
  (typeof MODALIDAD_OCUPACION_ESPORADICA)[keyof typeof MODALIDAD_OCUPACION_ESPORADICA]

export const ESTADO_MODALIDAD_OCUPACION = {
  ACTIVO: 'ACTIVO',
  SUSPENDIDO: 'SUSPENDIDO'
}

export type EstadoModalidadOcupacion = keyof typeof ESTADO_MODALIDAD_OCUPACION

export const ESTADO_MODALIDAD_OCUPACION_LABEL = {
  [ESTADO_MODALIDAD_OCUPACION.ACTIVO]: 'Activo',
  [ESTADO_MODALIDAD_OCUPACION.SUSPENDIDO]: 'Suspendido'
}
