export enum OCUPACION_ESTADO {
  ACTIVO = 'ACTIVO',
  FINALIZADO = 'FINALIZADO'
}

export const OCUPACION_ESTADO_LABEL = {
  [OCUPACION_ESTADO.ACTIVO]: 'Activo',
  [OCUPACION_ESTADO.FINALIZADO]: 'Finalizado'
}

export const OCUPACION_ESTADO_OPTIONS = [
  {
    label: OCUPACION_ESTADO_LABEL[OCUPACION_ESTADO.ACTIVO],
    value: OCUPACION_ESTADO.ACTIVO
  },
  {
    label: OCUPACION_ESTADO_LABEL[OCUPACION_ESTADO.FINALIZADO],
    value: OCUPACION_ESTADO.FINALIZADO
  }
] as const

export type OcupacionEstado =
  (typeof OCUPACION_ESTADO)[keyof typeof OCUPACION_ESTADO]
