export const PLAYERO_PLAYA_ESTADO = {
  ACTIVO: 'ACTIVO',
  SUSPENDIDO: 'SUSPENDIDO',
  PENDIENTE: 'PENDIENTE'
} as const

export type PLAYERO_PLAYA_ESTADO =
  (typeof PLAYERO_PLAYA_ESTADO)[keyof typeof PLAYERO_PLAYA_ESTADO]
